In [1]:
import numpy as np

# Магия, чтобы модуль experimental_net импортировался заново при изменениях в нём.
%reload_ext autoreload
%autoreload 2

import toy_net as nn

toy_net reload
toy_net.common reload
toy_net.functions reload
toy_net.optimizers reload
toy_net.net reload


In [2]:
print(nn.indent('aaa\nbbb\nccc'))

  aaa
  bbb
  ccc


In [3]:
# Matrix

test = nn.Layer(nn.Matrix(4, 3))
print(test)
test.func.w = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(test)
test.data.x = np.array([[100, 200, 300, 400], [500, 600, 700, 800]])
test.forward()
test.backward(np.array([[1, 0, -1], [1, 2, 3]]))
test.update(0.001)
print(test)
print(test.func.trace_statistics(test.data.x))
test.reset_batch_data()
print(test)

data:
  x:
    None
  y:
    None
  gx:
    None
  gy:
    None
  gw:
    None
func:
  w:
    [[ 0.09352466 -1.07407951  0.17438351]
     [-0.25495752  0.26009902  0.06663562]
     [ 0.2916001   0.02533651  0.83311381]
     [ 0.64810747  0.49485719 -0.71345285]]
  reg2:
    None
  reg2_constrain:
    None
  reg3:
    None
optimizer:
  SGD
data:
  x:
    None
  y:
    None
  gx:
    None
  gy:
    None
  gw:
    None
func:
  w:
    [[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [10 11 12]]
  reg2:
    None
  reg2_constrain:
    None
  reg3:
    None
optimizer:
  SGD
data:
  x:
    [[100 200 300 400]
     [500 600 700 800]]
  y:
    [[ 7000  8000  9000]
     [15800 18400 21000]]
  gx:
    [[-2 -2 -2 -2]
     [14 32 50 68]]
  gy:
    [[ 1  0 -1]
     [ 1  2  3]]
  gw:
    [[ 600 1000 1400]
     [ 800 1200 1600]
     [1000 1400 1800]
     [1200 1600 2000]]
func:
  w:
    [[  0.4   1.    1.6]
     [  3.2   3.8   4.4]
     [  6.    6.6   7.2]
     [  8.8   9.4  10. ]]
  reg2:
    None
  re

In [4]:
# NormalizeMean

test = nn.Layer(nn.MeanNorm())
test.data.x = np.array([[-1, 1, 2, 4], [3, 4, -10, 5]])
test.forward()
test.backward(np.array([[10, 10, 10, 10], [100, 100, 100, 100]]))
print(test)

data:
  x:
    [[ -1   1   2   4]
     [  3   4 -10   5]]
  y:
    [[-2.  -1.5  6.  -0.5]
     [ 2.   1.5 -6.   0.5]]
  gx:
    [[ 10  10  10  10]
     [100 100 100 100]]
  gy:
    [[ 10  10  10  10]
     [100 100 100 100]]
  gw:
    None
func:


In [5]:
# Reshape

test = nn.Layer(nn.Reshape([2, 3]))
test.data.x = np.arange(0, 12).reshape(2, 6)
test.forward()
test.backward(np.arange(0, 12).reshape(2, 2, 3))
print(test)

data:
  x:
    [[ 0  1  2  3  4  5]
     [ 6  7  8  9 10 11]]
  y:
    [[[ 0  1  2]
      [ 3  4  5]]
    
     [[ 6  7  8]
      [ 9 10 11]]]
  gx:
    [[ 0  1  2  3  4  5]
     [ 6  7  8  9 10 11]]
  gy:
    [[[ 0  1  2]
      [ 3  4  5]]
    
     [[ 6  7  8]
      [ 9 10 11]]]
  gw:
    None
func:


In [7]:
# Relu

test = nn.Layer(nn.Relu())
test.data.x = np.array([[-1, 1, 2], [3, 4, -10]])
test.forward()
test.backward(np.array([[10, 10, 10], [100, 100, 100]]))
print(test)

data:
  x:
    [[ -1   1   2]
     [  3   4 -10]]
  y:
    [[0 1 2]
     [3 4 0]]
  gx:
    [[   0.   10.   10.]
     [ 100.  100.    0.]]
  gy:
    [[ 10  10  10]
     [100 100 100]]
  gw:
    None
func:


In [8]:
# MaxPool

test = nn.Layer(nn.MaxPool())
test.data.x = np.array([[-1, 1, 2], [3, 4, -10]])
test.forward()
test.backward(np.array([[10, 10, 10], [100, 100, 100]]))
print(test)

data:
  x:
    [[ -1   1   2]
     [  3   4 -10]]
  y:
    [[-0.  0.  2.]
     [ 0.  4. -0.]]
  gx:
    [[   0.    0.   10.]
     [   0.  100.    0.]]
  gy:
    [[ 10  10  10]
     [100 100 100]]
  gw:
    None
func:


In [9]:
test = nn.Layer(nn.Dropout(0.2))
test.data.x = np.array([np.arange(10), np.arange(10, 20)])
test.forward()
test.backward(np.full((2, 10), 1))
print(test)

data:
  x:
    [[ 0  1  2  3  4  5  6  7  8  9]
     [10 11 12 13 14 15 16 17 18 19]]
  y:
    [[  0.     1.25   0.     3.75   5.     6.25   7.5    8.75  10.    11.25]
     [ 12.5   13.75   0.    16.25  17.5   18.75  20.    21.25  22.5   23.75]]
  gx:
    [[ 1.25  1.25  0.    1.25  1.25  1.25  1.25  1.25  1.25  1.25]
     [ 1.25  1.25  0.    1.25  1.25  1.25  1.25  1.25  1.25  1.25]]
  gy:
    [[1 1 1 1 1 1 1 1 1 1]
     [1 1 1 1 1 1 1 1 1 1]]
  gw:
    None
func:


In [10]:
test = nn.Layer(nn.GradNorm(0.1))
test.data.x = np.array([np.arange(10), np.arange(10, 20)])
test.forward()
test.backward(np.full((2, 10), 1))
print(test)


data:
  x:
    [[ 0  1  2  3  4  5  6  7  8  9]
     [10 11 12 13 14 15 16 17 18 19]]
  y:
    [[ 0  1  2  3  4  5  6  7  8  9]
     [10 11 12 13 14 15 16 17 18 19]]
  gx:
    [[ 0.00999001  0.00999001  0.00999001  0.00999001  0.00999001  0.00999001
       0.00999001  0.00999001  0.00999001  0.00999001]
     [ 0.00999001  0.00999001  0.00999001  0.00999001  0.00999001  0.00999001
       0.00999001  0.00999001  0.00999001  0.00999001]]
  gy:
    [[1 1 1 1 1 1 1 1 1 1]
     [1 1 1 1 1 1 1 1 1 1]]
  gw:
    None
func:


In [11]:
test = nn.Layer(nn.SoftMax())
test.data.x = np.array([[-1, 1, 2], [3, 4, 2]])
test.forward()
test.backward(np.array([[0, 0, 0.1], [0.1, 0.3, -0.5]]))
print(test)


data:
  x:
    [[-1  1  2]
     [ 3  4  2]]
  y:
    [[ 0.03511903  0.25949646  0.70538451]
     [ 0.24472847  0.66524096  0.09003057]]
  gx:
    [[-0.00247724 -0.01830448  0.02078172]
     [-0.01934085  0.0804743  -0.06113345]]
  gy:
    [[ 0.   0.   0.1]
     [ 0.1  0.3 -0.5]]
  gw:
    None
func:


In [12]:
test = nn.Layer(nn.SvmLoss())
test.func.set_ground(np.array([[1, 0, 0], [0, 1, 0]]))
test.data.x = np.array([[2, 3, 4], [0.5, 1, -2]])
test.forward()
test.backward(None)
print(test)


data:
  x:
    [[ 2.   3.   4. ]
     [ 0.5  1.  -2. ]]
  y:
    [ 2.5   0.25]
  gx:
    [[-1.   0.5  0.5]
     [ 0.5 -0.5  0. ]]
  gy:
    None
  gw:
    None
func:


In [13]:
test = nn.Layer(nn.EntropyLoss())
test.func.set_ground(np.array([[1, 0, 0], [0, 1, 0]]))
test.data.x = np.array([[2, 3, 4], [0.5, 1, -2]])
test.forward()
test.backward(None)
print(test)


data:
  x:
    [[ 2.   3.   4. ]
     [ 0.5  1.  -2. ]]
  y:
    [-0.34657359 -0.        ]
  gx:
    [[-0.25  0.    0.  ]
     [ 0.   -0.5   0.  ]]
  gy:
    None
  gw:
    None
func:


In [14]:
test = nn.Layer(nn.FixedLinear(0.1, 100))
test.data.x = np.array([[1, 2, 3], [0.5, 1, -2]])
test.forward()
test.backward(np.array([[1, 0, 0], [0, 1, 0]]))
print(test)

data:
  x:
    [[ 1.   2.   3. ]
     [ 0.5  1.  -2. ]]
  y:
    [[ 100.1   100.2   100.3 ]
     [ 100.05  100.1    99.8 ]]
  gx:
    [[ 10.   0.   0.]
     [  0.  10.   0.]]
  gy:
    [[1 0 0]
     [0 1 0]]
  gw:
    None
func:
  a:
    0.1
  b:
    100


In [20]:
test = nn.Layer(nn.BatchNorm())
test.data.x = np.array([[1, 2, 3], [7, 6, 5]])
test.forward()
print(test)

toy_net.functions reload
data:
  x:
    [[1 2 3]
     [7 6 5]]
  y:
    [[-1. -1. -1.]
     [ 1.  1.  1.]]
  gx:
    None
  gy:
    None
  gw:
    None
func:
  sigma:
    [[ 3.  2.  1.]]
