In [1]:
import numpy as np
import random
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 6)

In [2]:
# Пример трюков с массивами numpy
a = np.array([
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34]])
bs = np.array([0, 1, 2, 0, 1])
b = a[bs, np.arange(5)]
b

array([10, 21, 32, 13, 24])

In [ ]:
# Broadcast
x = np.array([1, 2, 3])

In [5]:
def rf_adjust_scalar(n, x):
    if np.isscalar(x):
        return np.full(n, x)
    else:
        return x

def test_rf_adjust_scalar():
    print("Test rf_adjust_scalar")
    a = rf_adjust_scalar(5, 0.5)
    print(a)
    print(rf_adjust_scalar(5, a))
    print(rf_adjust_scalar(5, 1))
    
def rf_adjust_scalars(n, array):
    adjusted = []
    for i, x in enumerate(array):
        adjusted.append(rf_adjust_scalar(n, x))
    return np.array(adjusted)

def test_rf_adjust_scalars():
    print("Test rf_adjust_scalars")
    print(rf_adjust_scalars(5, [0, 1, 2]))
    print(rf_adjust_scalars(5, [0.5, 0.2]))
    print(rf_adjust_scalars(5, [0.5, rf_adjust_scalar(5, 0.3)]))

def rf_random(n):
    return np.random.random(n)

def test_rf_random():
    print("Test rf_random")
    print(rf_random(5))

def rf_discrete(n, distribution):
    p_array = rf_adjust_scalars(n, distribution)
    p_sum = sum(p_array)
    r = np.random.random(n) * p_sum
    threshold = np.zeros(n);
    result = np.zeros(n, dtype='int')
    for i, p in enumerate(p_array):
        result[r >= threshold] = i
        threshold = threshold + p
    return result

def test_rf_discrete():
    print("Test rf_discrete")
    print(rf_discrete(10, [0.5, 0.7]))
    p = rf_random(10)
    print(p)
    print(rf_discrete(10, [1 - p, p]))

# ToDo: Должен быть режимом rf_discrete
def rf_binary(n, one_probability):
    return rf_discrete(n, [1 - one_probability, one_probability])

def rf_select(indexes, sources):
    n = len(indexes)
    adjusted = np.array(rf_adjust_scalars(n, sources))
    return adjusted[np.array(indexes), np.arange(n)]

def test_rf_select():
    print("Test rf_select")
    a = [0, 0, 1, 1, 2, 2]
    print(rf_select(a, [10, 20, 30]))

# ToDo: Должен быть rf_pselect когда rf_binary будет режимом rf_discrete
def rf_dnoise(p, signal, noise):
    is_noise = rf_binary(len(signal), p)
    return rf_select(is_noise, [signal, noise])

def rf_salt(p, a):
    return rf_dnoise(p, a, 0)

def rf_pepper(p, a):
    return rf_dnoise(p, a, 1)

def test():
    print("Test begin")
    test_rf_adjust_scalar()
    test_rf_adjust_scalars()
    test_rf_random()
    test_rf_discrete()
    test_rf_select()
    print("Test end")
    print()

test()

Test begin
Test rf_adjust_scalar
[ 0.5  0.5  0.5  0.5  0.5]
[ 0.5  0.5  0.5  0.5  0.5]
[1 1 1 1 1]
Test rf_adjust_scalars
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
[[ 0.5  0.5  0.5  0.5  0.5]
 [ 0.2  0.2  0.2  0.2  0.2]]
[[ 0.5  0.5  0.5  0.5  0.5]
 [ 0.3  0.3  0.3  0.3  0.3]]
Test rf_random
[ 0.37311043  0.48267268  0.19743692  0.30483454  0.30043577]
Test rf_discrete
[1 1 1 1 1 1 0 1 1 1]
[ 0.77274431  0.15661904  0.21644756  0.12578781  0.00332327  0.14953721
  0.43050032  0.76514491  0.44345878  0.5506255 ]
[1 0 0 0 0 0 1 1 0 0]
Test rf_select
[10 10 20 20 30 30]
Test end



In [457]:
n = 30

#a = rf_discrete(n, [0.7, 0.2, 0.1])
a = np.concatenate((np.full(10, 0), np.full(10, 1), np.full(10, 2)))
print("a:")
print(y)
print()

b1 = rf_select(a, [1, 0, 0])
b2 = rf_select(a, [1, 0, 0])
b3 = rf_select(a, [1, 1, 0])
b4 = rf_select(a, [0, 1, 0])
b5 = rf_select(a, [0, 1, 1])
b6 = rf_select(a, [0, 0, 1])
b7 = rf_select(a, [0, 0, 1])
print("bi:")
print(b1)
print(b2)
print(b3)
print(b4)
print(b5)
print(b6)
print(b7)
print()

noise_p = rf_random(n) / 2
print("noise probability:")
print(noise_p)
print()

c1 = b1
c2 = rf_salt(0.2, rf_pepper(noise_p, b2))
c3 = rf_select(rf_binary(n, noise_p), [b3, rf_binary(n, 0.5)])
c4 = rf_dnoise(noise_p, b4, rf_binary(n, 0.5))
c5 = rf_salt(0.2, rf_pepper(0.2, b5))
c6 = rf_salt(noise_p, rf_pepper(0.2, b6))
c7 = rf_salt(noise_p, rf_pepper(0.2, b7))
print("ci:")
print(c1)
print(c2)
print(c3)
print(c4)
print(c5)
print(c6)
print(c7)
print()

a:
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]

bi:
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]

noise probability:
[ 0.16378197  0.07208215  0.08280643  0.48196526  0.48011336  0.09420733
  0.01215328  

In [458]:
x = np.array([c1, c2, c3, c4, c5, c6, c7]).transpose()
print('x:\n', x)

y = np.eye(3)[a]
print('y:\n', y)

x:
 [[1 1 1 0 0 0 0]
 [1 1 1 0 0 0 1]
 [1 1 1 0 0 0 0]
 [1 0 0 0 1 0 0]
 [1 1 1 1 0 0 0]
 [1 1 1 0 0 0 0]
 [1 0 1 0 0 1 1]
 [1 1 1 0 0 1 0]
 [1 1 1 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 1 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 1 0]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1]
 [0 1 0 1 0 0 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 0 1]
 [0 0 0 0 1 0 1]
 [0 1 1 0 1 1 0]
 [0 0 1 0 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]]
y:
 [[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]


In [446]:
np.random.seed(5)
W = np.random.rand(x.shape[1], y.shape[1]) - 0.5
B = np.random.rand(y.shape[1]) - 0.5

prev_loss = 0

In [500]:
speed = 0.01

W_in = x
W_out = np.dot(W_in, W)
B_in = W_out
B_out = B_in + B
y_pred = B_out

#print('y_pred:\n', y_pred)

def calculate_accuracy(x, y):
    W_in = x
    W_out = np.dot(W_in, W)
    B_in = W_out
    B_out = B_in + B
    y_pred = W_out
    return np.mean(np.argmax(y_pred, axis=1) == np.argmax(y, axis=1))

def calculate_loss():
    value_of_true = np.sum(y_pred * y, axis=1)
    result = y_pred + 1 - value_of_true.reshape(-1, 1)
    result = np.maximum(result, 0)
    result[np.arange(result.shape[0]), np.argmax(y, axis=1)] = 0
    return np.sum(result)

def calculate_loss_grad():
    result = np.sum(y_pred * y, axis=1)
    result = y_pred - y + 1 - result.reshape(-1, 1)
    result = np.maximum(result, 0)
    result[result > 0.00001] = 1
    result[np.arange(result.shape[0]), np.argmax(y, axis=1)] = -np.sum(result, axis=1)
    return result;

loss = calculate_loss()
print('Loss:', loss)
print('Loss change:', loss - prev_loss)
prev_loss = loss

print('Accuracy:', calculate_accuracy(x, y))

grad = calculate_loss_grad()
#print('grad:\n', grad)

#print('grad sum:', np.sum(grad, axis=0))
#print('B before:', B)

B = B - speed * np.sum(grad, axis=0)
W = W - speed * np.dot(W_in.transpose(), grad)
W = W - 0.1 * W * np.abs(W)

print('W:\n', W)
print('B:\n', B)

Loss: 2.40270976536
Loss change: 0.124819715055
Accuracy: 1.0
W:
 [[ 0.72033644 -0.48232257 -0.5803344 ]
 [-0.0624794  -0.340327    0.37310394]
 [ 0.25422803  0.26257097 -0.35597895]
 [-0.28744691  0.3933505  -0.29702832]
 [-0.28806667  0.12790672  0.25610363]
 [-0.2061311  -0.26821159  0.31625444]
 [-0.07557264 -0.45861546  0.45369217]]
B:
 [-0.23418088 -0.21531412 -0.24641179]


In [423]:
#q_true = np.sum(y_pred * y, axis=1)
#q_true
#q_best = np.max(y_pred - y, axis=1)
#loss_vector = np.maximum(q_best - q_true, 0)
#np.sum(loss_vector)
a = np.array([[1], [2], [3]])
b = np.array([[1, 2], [3, 4], [5, 6]])

print(y)
print(y_pred)
result = np.sum(y_pred * y, axis=1)
result = y_pred - y + 1 - result.reshape(-1, 1)
result = np.maximum(result, 0)
result[result > 0.00001] = -1
result[np.arange(result.shape[0]), np.argmax(y, axis=1)] = -np.sum(result, axis=1)
print(result)

#grad = loss > 0.00001
#print(grad)
#print(grad)

#loss = np.maximum(loss, 0)
#loss[np.arange(loss.shape[0]), np.argmax(y, axis=1)] = 0
#(y - np.eye(y.shape[1])[np.argmax(y_pred - y, axis=1)]) / y.shape[0]


[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
[[-0.24627985  0.17383617 -0.74289214]
 [-0.24627985  0.17383617 -0.74289214]
 [ 0.17233105  0.16224736 -0.63114827]
 [ 0.17233105  0.16224736 -0.63114827]
 [-0.24627985  0.17383617 -0.74289214]
 [ 0.17233105  0.16224736 -0.63114827]
 [ 0.11364028 -0.17944277 -0.25121124]
 [ 0.07936833 -0.96943381  0.2805099 ]
 [-0.21045467 -0.87800718  0.26869523]
 [ 0.3916471  -0.55017507  0.0420696 ]
 [-0.33924257 -0.957845    0.16876603]
 [-0.33924257 -0.957845    0.16876603]
 [-0.33924257 -0.957845    0.16876603]
 [-0.21045467 -0.87800718  0.26869523]
 [-0.38999729 -0.56293142  0.02953437]
 [-0.38999729 -0.56293142  0.02953437]
 [-0.16408375 -0.47716644  0.23345443]
 [-0.18653952 -0.98785179  0.4837094

In [415]:
a = np.array([[1], [2], [3]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = np.array([0, 1, 1])
b[np.arange(3), c]

array([1, 4, 6])