https://docs.scipy.org/doc/numpy-dev/user/quickstart.html - Quick start

https://docs.scipy.org/doc/numpy/reference/routines.math.html - Список математических функций np

In [61]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

linspace(start, stop, num) - возвращает массив, заполненный арифметической прогрессией от start до stop включительно, количество элементов - num (по умолчанию 50).

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [119]:
np.linspace(0, 10, 10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

arange(start, stop, step) - массив значений, равномерно распределённых в интервале [start, stop), с шагом step. Минус arange в том, что stop не добавляется в массив.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

In [120]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.arange(0, 30, 1).reshape(3, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [28]:
np.random.random((2, 3))

array([[ 0.06339588,  0.35278078,  0.78048394],
       [ 0.47439248,  0.13447678,  0.99483393]])

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a.sum()

21

In [35]:
a.max()

6

In [36]:
a.sum(axis=0)

array([5, 7, 9])

In [37]:
a.sum(axis=1)

array([ 6, 15])

In [39]:
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [43]:
a = np.arange(5)
b = np.arange(5)
a + b

array([0, 2, 4, 6, 8])

In [55]:
a = np.array([[x + 10 * y for y in np.arange(5)] for x in np.arange(4)])
a

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [56]:
def f(x, y):
    return x + 10 * y
np.fromfunction(f, (4, 5))

array([[  0.,  10.,  20.,  30.,  40.],
       [  1.,  11.,  21.,  31.,  41.],
       [  2.,  12.,  22.,  32.,  42.],
       [  3.,  13.,  23.,  33.,  43.]])

In [57]:
np.fromfunction(lambda x, y: x + 10 * y, (4, 5))

array([[  0.,  10.,  20.,  30.,  40.],
       [  1.,  11.,  21.,  31.,  41.],
       [  2.,  12.,  22.,  32.,  42.],
       [  3.,  13.,  23.,  33.,  43.]])

In [58]:
for row in a:
    print(row)

[ 0 10 20 30 40]
[ 1 11 21 31 41]
[ 2 12 22 32 42]
[ 3 13 23 33 43]


## Трюки с индексами
### Параллельный массив bool

Зануляем отрицательные числа

In [106]:
x = np.linspace(0, 5*np.pi)
y = np.floor(100*np.sin(x))
print(y)
b = y < 0
print(b)
c = y[b]
print(c)
y[b] = 0
print(y)

[   0.   31.   59.   82.   95.   99.   93.   78.   54.   25.   -7.  -38.
  -65.  -86.  -98. -100.  -92.  -75.  -50.  -20.   12.   43.   69.   88.
   98.   98.   88.   69.   43.   12.  -20.  -50.  -75.  -92. -100.  -98.
  -86.  -65.  -38.   -7.   25.   54.   78.   93.   99.   95.   82.   59.
   31.    0.]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False]
[  -7.  -38.  -65.  -86.  -98. -100.  -92.  -75.  -50.  -20.  -20.  -50.
  -75.  -92. -100.  -98.  -86.  -65.  -38.   -7.]
[  0.  31.  59.  82.  95.  99.  93.  78.  54.  25.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.  12.  43.  69.  88.  98.  98.  88.  69.  43.  12.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  25.  54.  78.  93.  99.
  95.  82.  59.  31.   0.]


Изменяем только положительные числа:

In [114]:
x = np.linspace(0, 5*np.pi)
y = np.floor(100*np.sin(x))
y[y > 0] *= 10
print(y)

[   0.  310.  590.  820.  950.  990.  930.  780.  540.  250.   -7.  -38.
  -65.  -86.  -98. -100.  -92.  -75.  -50.  -20.  120.  430.  690.  880.
  980.  980.  880.  690.  430.  120.  -20.  -50.  -75.  -92. -100.  -98.
  -86.  -65.  -38.   -7.  250.  540.  780.  930.  990.  950.  820.  590.
  310.    0.]


In [118]:
np.ogrid[-5:5]

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])